### ISSUE TITLE
DDANAT rearguard cell issues

### ISSUE THREAD

**Issue by cmungall** [dictyBase/migration-data#2]
```
[Term]
id: DDANAT:0000409
name: rearguard cell
namespace: Dictyostelium_discoideum_anatomy
alt_id: DDANAT:0000024
def: "Cell expressing ecmB but not ecmA. Rearguard cells are located at the very rear of the slug (rearguard region). These cells form the outer basal disc of the fruiting body. If a migratory slug is formed, these cells are left behind." [DDB:pg, PMID:8631253]
synonym: "prestalk B cell" EXACT []
synonym: "pstB cell" RELATED []
xref: CL:0000275
is_a: DDANAT:0000404  ! anterior like cell
relationship: part_of DDANAT:0000025 ! basal region of the standing slug
relationship: part_of DDANAT:0000034 ! posterior region of the migratory slug
relationship: part_of DDANAT:0000045 ! basal region of the early culminant
relationship: part_of DDANAT:0000057 ! basal disc of the mid culminant
relationship: part_of DDANAT:0000067 ! outer basal disc of the late culminant
relationship: part_of DDANAT:0000072 ! lower cup of the fruiting body
relationship: part_of DDANAT:0000075 ! outer basal disc of the fruiting body
```

What this means is that every instance of a rearguard cell is simultaneously an instance of all of these things. I think you mean that is *can* be an instance of any of these.

Why does this matter?

Let's say you have a gene G expressed in a rearguard cell but only in the mid-culminant stage (no idea if this is a realistic example). I guess here you would make two annotations, but separate.

Now let's say someone comes along and queries for `outer basal disc of the late culminant`. They would get G, due to the graph structure and the 'true path rule' (for expression, following isa and partof). However, G would not be valid.

If this is not  a concern feel free to close this ticket, just a FYI

**Comment by pfey03** [comment]
Hi Chris,

We do currently not use the DDANAT for direct annotations (as we do not yet annotate expression), we use the terms in our pre-composed phenotype ontology if required. However, I do see your point and we might very well use it after our database overhaul. 

I think the consequence of your thinking would mean to create separate terms, such as "rearguard cell of the basal disc of the mid culminate" etc. That would blow up the ontology and I'm sure the same might apply to other cell types. 

Since Pascale was the lead on this with Jeff Williams a Dicty Dev. Biologist when it was first published, I need to include her in this discussion.

Thanks!

@pgaudet

**Comment by pgaudet** [comment]
Hi Chris, 

The Dicty anatomy is very small so it may be structured in an non-orthodox manner: we have all the anatomical parts, down to the cell level, and all the developmental stages in the same ontology. 

Are you suggested we should also have created 'rearguard cell of the late culminant', and other terms at that level of granularity  ? 

If that's the case: that does seem ontologically more appropriate. However in Dicty these cell types were defined by the markers they expressed, so if cells start expressing new genes (or stop expressing certain genes), then a new cell type was defined. I am not sure that *always* hold, but that hold most of the time. 

My view was that we should keep it simple until the need arises to justify adding this level of complexity; what do you think ? 

Cheers, 
Pascale

**Comment by cmungall** [comment]
On 18 Feb 2015, at 9:34, pgaudet wrote:

> Hi Chris,
>
> The Dicty anatomy is very small so it may be structured in an 
> non-orthodox manner: we have all the anatomical parts, down to the 
> cell level, and all the developmental stages in the same ontology.

This is perfectly fine

> Are you suggested we should also have created 'rearguard cell of the 
> late culminant', and other terms at that level of granularity  ?

That is one approach.

Another is that you remove the existing part_ofs and post-compose in 
your annotations; e.g. expressed in 'rearguard cell' and part_of some 
'late culminant'

But that is a lot of overhead to invoke for what might be a corner case

> If that's the case: that does seem ontologically more appropriate. 
> However in Dicty these cell types were defined by the markers they 
> expressed, so if cells start expressing new genes (or stop expressing 
> certain genes), then a new cell type was defined. I am not sure that 
> *always* hold, but that hold most of the time.

That's a good criterion to have

> My view was that we should keep it simple until the need arises to 
> justify adding this level of complexity; what do you think ?

Fair enough. If the additional precision isn't worth the overhead then 
don't bother

There is still the question of what to do with the existing part_ofs - I 
can see these being useful for navigation. But they may also give false 
positives in queries (not sure how to quickly query the data to find 
examples, so if this doesn't seem like a major concern this can be 
closed)

**Comment by pfey03** [comment]
Thanks Pascale, I thought about the marker expression but wasn't sure if this was pretty much always the case.

I would suggest we leave as is for now then and I'm closing this issue. However, should we start using this ontology directly for (expression) annotations in the future, and If I find anything that resembles Chris' hypothetical annotation, I will come back to it and we may add more complexity. Nice it's here in GitHub.
