### ISSUE TITLE
loading issues with dicty ontologies

### ISSUE THREAD

**Issue by cybersiddhu** [dictyBase/migration-data#4]
cc: @pfey03 

Both `dicty_anatomy.obo` and `plasmid_keywords.obo` failed to load in chado database. I have given the reason of the failure and possible minor fixes that i expect to solve the loading failures.
### dicty_anatomy.obo

The `alt_id` [here](https://github.com/dictyBase/migration-data/blob/master/ontologies/dicty_anatomy.obo#L967) points to an existing term [here](https://github.com/dictyBase/migration-data/blob/master/ontologies/dicty_anatomy.obo#L73). As far as i understand, the `alt_id` cannot be an existing id.

The possible fix would be either to delete the `alt_id` or point to an removed id(if that is the case)
### plasmid_keywords.obo

It lacks a `default-namespace` header. For example `plasmid_inventory.obo` has [one](https://github.com/dictyBase/migration-data/blob/master/ontologies/plasmid_inventory.obo#L5).

The fix is to add `default-namespace` header.

**Comment by cybersiddhu** [comment]
### dicty_envirornment.obo and dicty_assay.obo
Both of them contains terms for each other namespaces, for examples `dicty_environment` has the term [DDASSAY:0000003](https://github.com/dictyBase/migration-data/blob/master/ontologies/dicty_environment.obo#L8) for `dicty_assay` that is also present in `dicty_assay` with a different [name](https://github.com/dictyBase/migration-data/blob/master/ontologies/dicty_assay.obo#L8).  You can also find `dicty_environment` terms(prefixed with DDENVIR) in `dicty_assay`.

Having the identical id with identical namespace in different ontologies prevent them from getting loaded in chado. Presence of one id in database blocks the other as it breaks the unique constraints. 

The fix will be keep the ids in their correct namespaces and do not share them in other ontologies. 

__Note:__  Though technically it is allowed and common practice to import cross ontologies and borrow and mix terms from other namespaces, but i am not sure if it is the case here.

**Comment by pfey03** [comment]
First the DDASSAY issue in the DDENVIR ontology: DDASSAY:0000003 is OBSOLETE! If it helps we can completely delete/ get rid of it! It was added  by mistake (ages ago) with the wrong ID (IDs always stick from the last edited ontology in OBOEdit). As I said, I can destroy the term if you want, or you can from your end if you prefer.

**Comment by pfey03** [comment]
### dicty_anatomy.obo
I think there are at least  two cases of alt_Ids pointing to exiting term:

id: DDANAT:0000403
name: aggregate cell
alt_id: DDANAT:0000009

id: DDANAT:0000404
name: anterior like cell
alt_id: DDANAT:0000019

I think we should delete these alternate IDs. Not sure I can do that in OBOEdit. Can you delete them? And tell me if you find more than these two?

**Comment by pfey03** [comment]
### plasmid_keywords.obo

Yes, adding default name space is ok

**Comment by pfey03** [comment]
### Naming of newer ontologies

I have thought that maybe all or small ontologies should start with dicty like the established one. E.g dicty_plasmid_keywords.obo, dicty_strain_inventory.obo, etc. Just when thinking ahead and Chris might make them all public. Would that be a problem?

**Comment by cybersiddhu** [comment]
## DDASSAY
Getting rid should be the best, preferably use OBO-Edit, if it creates any more problem, then i will delete them manually. I am just conservative in editing obo file manually.

## dicty_anatomy
Will delete them

## Renaming ontologies
It should be fine, no problem

**Comment by pfey03** [comment]
## DDASSAY
Will destroy them in OBOedit

## dicty_anatomy
Great!

## Renaming ontologies
In GIt, when I go to the ontologies I can delete them. If I rename I think that would be best, do you agree? Delete them all (just those that need renaming), rename on my computer, and add them to Git anew. We loose the history there but no big deal. I have older versions anyhow.

**Comment by pfey03** [comment]
## DDENVIR
Updated (obsolete DDASSAY term destroyed)

**Comment by pfey03** [comment]
## Renaming ontologies

It's much easier.Renamed in local Github and synched, no problem. All my ontologies now have the dicty_ prefix. The literature topic has dictybase and that's fine. Won't fiddle with that.

This, from my end, fixes all issues

**Comment by cybersiddhu** [comment]
Tied to https://github.com/dictyBase/Modware-Loader/issues/162

**Comment by cybersiddhu** [comment]
The `dicty_assay.obo` file still has two dicty environmental terms [here](https://github.com/dictyBase/migration-data/blob/master/ontologies/dicty_assay.obo#L453) and [here](https://github.com/dictyBase/migration-data/blob/master/ontologies/dicty_assay.obo#L460) under DDENVDIR namespaces. Should they be removed and if so i could do that.
Let me know.

**Comment by pfey03** [comment]
I fixed the ontology and terms were important. Destroyed those terms and created new with correct ID. File now ok and sorry for that.

**Comment by cybersiddhu** [comment]
Thanks.
Everything is completed.

**Comment by cybersiddhu** [comment]
#dicty_assay.obo
Still contain cross ontology term, this time its from `dicty_phenotypes.obo`. The term [here](https://github.com/dictyBase/migration-data/blob/master/ontologies/dicty_assay.obo#L467) literally overlaps with [this](https://github.com/dictyBase/migration-data/blob/master/ontologies/dicty_phenotypes.obo#L8) one. They have identical ontology ids `DDPHENO:0000001` with different names with a different graph path. This is not acceptable for loading.

**Comment by pfey03** [comment]
Fixed!

**Comment by cybersiddhu** [comment]
The `dicty_environment.obo` is broken now, cannot be loaded in database.
You might have reverted my [commit](https://github.com/dictyBase/migration-data/commit/8fe8165f2b5ce657473fbf057b4cdfba506d2ee8) that did took care of the problem. You have to remove those two alt_ids.

**Comment by pfey03** [comment]
These are things I never fixed or you hard code took them out and I didn't know. Since I'm used to be the only one editing. There are two DDASSAY alt ids. I can either 1) hard code and just delete and save back (easiest), or in 2) OBOedit, I cannot delete alt_id, I don't want to OBSOLETE the terms and keep as bulk, so I would DESTROY the terms and re-eneter new terms. 

What do you prefer?

**Comment by pfey03** [comment]
Also, I thought only I make commits these days, that's why I don't check them out before. Tell me if you do any fix so I know. But these IDs have never been removed I think. If I don't hear from you then I do hard fix without OBOedit eventually today as it's fastest and clean. Can change the date/time stamp as well and otherwise leave header.

**Comment by pfey03** [comment]
it's fixed now and here available

**Comment by cmungall** [comment]
can this be closed?

**Comment by pfey03** [comment]
I think so but checking with @cybersiddhu . Will close when I hear back
