### ISSUE TITLE
Fix phenotype annotation

### ISSUE THREAD

**Issue by cybersiddhu** [dictyBase/migration-data#63]
In this annotation....
http://dictybase.org/db/cgi-bin/dictyBase/phenotype/strain_and_phenotype_details.pl?genotype_id=775
`in the absense of EDTA` term should be  __in the absence of EDTA__
![Screenshot 2022-07-25 at 15-27-13 Phenotype and Strain Details for talA-](https://user-images.githubusercontent.com/48740/180868370-2fc7cd27-e329-4e8d-ae05-35e2dcbc02cd.png)

@pfey03

**Comment by pfey03** [comment]
@cybersiddhu 
I fixed the annotation, the absence term is a synonym, don't ask me why! Must be ancient I didn't add it.

A question, can I delete the synonym and submit the environment ontology or should I rather wait doing that?

**Comment by pfey03** [comment]
I didn't know there were two strains, but fixed stream 774 as well now
